W0321 21:08:45.076000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py:793] 
W0321 21:08:45.076000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
W0321 21:08:45.076000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0321 21:08:45.076000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py:793] *****************************************
[2025-03-21 21:08:52,229] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-21 21:08:52,251] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-21 21:08:52,253] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2025-03-21 21:08:52,255] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
INFO 03-21 21:08:56 __init__.py:190] Automatically detected platform cuda.
INFO 03-21 21:08:56 __init__.py:190] Automatically detected platform cuda.
INFO 03-21 21:08:56 __init__.py:190] Automatically detected platform cuda.
INFO 03-21 21:08:56 __init__.py:190] Automatically detected platform cuda.
Traceback (most recent call last):
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/grpo_vllm.py", line 25, in <module>
Traceback (most recent call last):
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/grpo_vllm.py", line 25, in <module>
    from trainer.grpo_trainer_vllm import Qwen2VLGRPOTrainer
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/__init__.py", line 1, in <module>
Traceback (most recent call last):
        from trainer.grpo_trainer_vllm import Qwen2VLGRPOTrainer  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/grpo_vllm.py", line 25, in <module>
from .grpo_trainer_vllm import Qwen2VLGRPOTrainer

  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/grpo_trainer_vllm.py", line 51, in <module>
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/__init__.py", line 1, in <module>
        from trainer.grpo_trainer_vllm import Qwen2VLGRPOTrainerfrom .grpo_trainer_vllm import Qwen2VLGRPOTrainer
Traceback (most recent call last):

  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/__init__.py", line 1, in <module>
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/grpo_vllm.py", line 25, in <module>
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/grpo_trainer_vllm.py", line 51, in <module>
    from .grpo_trainer_vllm import Qwen2VLGRPOTrainer    
from qwen_vl_utils import process_vision_info
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/grpo_trainer_vllm.py", line 51, in <module>
    ModuleNotFoundErrorfrom trainer.grpo_trainer_vllm import Qwen2VLGRPOTrainer: 
No module named 'qwen_vl_utils'
    from qwen_vl_utils import process_vision_info  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/__init__.py", line 1, in <module>

ModuleNotFoundError: No module named 'qwen_vl_utils'
    from .grpo_trainer_vllm import Qwen2VLGRPOTrainer
  File "/ocean/projects/cis210027p/qwang20/R1-Multimodal-Journey/src/open_r1/trainer/grpo_trainer_vllm.py", line 51, in <module>
    from qwen_vl_utils import process_vision_info
ModuleNotFoundError: No module named 'qwen_vl_utils'
    from qwen_vl_utils import process_vision_info
ModuleNotFoundError: No module named 'qwen_vl_utils'
W0321 21:08:57.817000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 19405 closing signal SIGTERM
W0321 21:08:57.818000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:897] Sending process 19406 closing signal SIGTERM
E0321 21:08:58.063000 19354 /ocean/projects/cis210027p/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 2 (pid: 19407) of binary: /jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/bin/python
Traceback (most recent call last):
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/qwang20/miniconda3/envs/open_r1_mm_fix/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
src/open_r1/grpo_vllm.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-03-21_21:08:57
  host      : w004.ib.bridges2.psc.edu
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 19408)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-03-21_21:08:57
  host      : w004.ib.bridges2.psc.edu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 19407)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
